# Generated by Django 4.1.6 on 2023-02-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkbox',
            old_name='is_cheked',
            new_name='is_checked',
        ),
    ]
